set -g extended-keys on
set -g mouse on
setw -g mode-keys vi
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g allow-passthrough on
set -as terminal-features 'xterm*:extkeys'
set -g status-position top
set -g focus-events on

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection
bind-key C-k send-keys C-l \; clear-history

set -g status-left '#{?client_prefix,#[bg=yellow]#[fg=black] ⌨ #[default],#[bg=green] #S }'
